apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podreader
rules:
- apiGroups: [""] 
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
- kind: User
  name: ivan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: podreader
  apiGroup: rbac.authorization.k8s.io
